---
version: '3'

services:
  shared-database:
    image: postgres
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_MULTIPLE_DATABASES: ccd,ccd_user_profile,ccd_definition,ccd_data,evidence,ccd_definition_designer,divorce
      DB_USERNAME:
      DB_PASSWORD:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5050:5432

  ccd-user-profile-api:
    image: "${CCD_USER_PROFILE_API_USE_LOCAL-hmctspublic.azurecr.io/}ccd/user-profile-api:${CCD_USER_PROFILE_API_TAG:-latest}"
    environment:
      JAVA_TOOL_OPTIONS: -Xms128m -Xmx400m
      USER_PROFILE_DB_HOST: shared-database
      USER_PROFILE_DB_PORT: 5432
      USER_PROFILE_DB_USERNAME: "${DB_USERNAME}"
      USER_PROFILE_DB_PASSWORD: "${DB_PASSWORD}"
      USER_PROFILE_DB_USE_SSL: "false"
      USER_PROFILE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_definition,ccd_admin
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - 4453:4453
    depends_on:
      - shared-database
      - service-auth-provider-api

  ccd-definition-store-api:
    image: "${CCD_DEFINITION_STORE_API_USE_LOCAL-hmctspublic.azurecr.io/}ccd/definition-store-api:${CCD_DEFINITION_STORE_API_TAG:-latest}"
    environment:
      JAVA_TOOL_OPTIONS: -Xms128m -Xmx400m
      DEFINITION_STORE_DB_HOST: shared-database
      DEFINITION_STORE_DB_PORT: 5432
      DEFINITION_STORE_DB_USERNAME: "${DB_USERNAME}"
      DEFINITION_STORE_DB_PASSWORD: "${DB_PASSWORD}"
      DEFINITION_STORE_DB_USE_SSL: "false"
      DEFINITION_STORE_IDAM_KEY: AAAAAAAAAAAAAAAA
      DEFINITION_STORE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_gw,ccd_admin,probate_backend
      USER_PROFILE_HOST: http://ccd-user-profile-api:4453
      IDAM_USER_URL: https://idam-web-public.aat.platform.hmcts.net
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      REFORM_SERVICE_NAME: ccd-definition-store-api
      ELASTIC_SEARCH_ENABLED: "true"
      ELASTIC_SEARCH_HOST: "ccd-elasticsearch"
      ELASTIC_SEARCH_FAIL_ON_IMPORT: "true"
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - 4451:4451
    depends_on:
      - shared-database
      - ccd-user-profile-api
      - service-auth-provider-api

  ccd-data-store-api:
    image: "${CCD_DATA_STORE_API_USE_LOCAL-hmctspublic.azurecr.io/}ccd/data-store-api:${CCD_DATA_STORE_API_TAG:-latest}"
    environment:
      JAVA_TOOL_OPTIONS: -Xms128m -Xmx400m
      DATA_STORE_DB_HOST: shared-database
      DATA_STORE_DB_PORT: 5432
      DATA_STORE_DB_USERNAME: "${DB_USERNAME}"
      DATA_STORE_DB_PASSWORD: "${DB_PASSWORD}"
      DATA_STORE_DB_USE_SSL: "false"
      DATA_STORE_IDAM_KEY: AAAAAAAAAAAAAAAA
      DATA_STORE_TOKEN_SECRET: AAAAAAAAAAAAAAAA
      DATA_STORE_S2S_AUTHORISED_SERVICES: ccd_gw,fpl_case_service,ccd_data,ccd_ps,probate_backend,payment-api
      CCD_DM_DOMAIN: http://dm-store:8080
      DEFINITION_STORE_HOST: http://ccd-definition-store-api:4451
      USER_PROFILE_HOST: http://ccd-user-profile-api:4453
      IDAM_USER_URL: https://idam-web-public.aat.platform.hmcts.net
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      ELASTIC_SEARCH_ENABLED: "true"
      ELASTIC_SEARCH_HOSTS: ccd-elasticsearch:9200
      ELASTIC_SEARCH_DATA_NODES_HOSTS: "http://ccd-elasticsearch:9200"
      DATA_STORE_DEFAULT_LOG_LEVEL: INFO
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - 4452:4452
      - 5005:5005
    depends_on:
      - shared-database
      - ccd-user-profile-api
      - ccd-definition-store-api
      - service-auth-provider-api

  ccd-api-gateway:
    image: hmctspublic.azurecr.io/ccd/api-gateway-web:latest
    environment:
      IDAM_BASE_URL: https://idam-api.aat.platform.hmcts.net
      IDAM_USER_URL: https://idam-api.aat.platform.hmcts.net
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      IDAM_SERVICE_KEY: AAAAAAAAAAAAAAAA
      IDAM_OAUTH2_LOGOUT_ENDPOINT: https://idam-api.aat.platform.hmcts.net/session/:token
      IDAM_OAUTH2_CLIENT_ID: ccd_gateway
      IDAM_OAUTH2_CLIENT_SECRET: ccd_gateway_secret
      IDAM_OAUTH2_TOKEN_ENDPOINT: https://idam-api.aat.platform.hmcts.net/oauth2/token
      PROXY_DOCUMENT_MANAGEMENT: http://dm-store:8080
      ADDRESS_LOOKUP_TOKEN:
      PROXY_AGGREGATED: http://ccd-data-store-api:4452
      PROXY_DATA: http://ccd-data-store-api:4452
      PROXY_DEFINITION_IMPORT: http://ccd-definition-store-api:4451
      PROXY_DEFINITION_DATA: http://ccd-definition-store-api:4451/api/data
      PROXY_DEFINITION_DISPLAY: http://ccd-definition-store-api:4451/api/display
      PROXY_PAYMENTS: http://payments-api:8080
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - 3453:3453
    depends_on:
      - ccd-user-profile-api
      - ccd-definition-store-api
      - ccd-data-store-api
      - dm-store

  service-auth-provider-api:
    image: "hmctspublic.azurecr.io/rpe/service-auth-provider:latest"
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      JAVA_TOOL_OPTIONS: -Xms128m -Xmx256m
      SERVER_PORT: 8080
      JWT_KEY: wThK0f0/lh3FlxFcL4xUWDMI5C1J9KyQBgXV4wseh1e5J1uYJIjvTvArHxQDrYoHJ23xFxjHkOnvNbR5dXRoxA==
      MICROSERVICEKEYS_CCD_DATA: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_CCD_GW: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_CCD_DEFINITION: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_CCD_ADMIN: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_FPL_CASE_SERVICE: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_EM_GW: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_BULK_SCAN_PROCESSOR: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_BULK_SCAN_PROCESSOR_TESTS: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_BULK_SCAN_ORCHESTRATOR: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_PROBATE_BACKEND: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_PROBATE_FRONTEND: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_DG_DOCASSEMBLY_API: "AAAAAAAAAAAAAAAA"
      MICROSERVICE_KEYS_RPA_DG_DOCASSEMBLY: "AAAAAAAAAAAAAAAA"
      TESTING_SUPPORT_ENABLED: "true"
    ports:
      - 4502:8080

  ccd-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    environment:
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx400m
      - ES_JAVA_OPTS= -Xms128m -Xmx400m
      - cluster.name=ccd-docker-es-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - action.auto_create_index=.security*,.watches,.triggered_watches,.watcher-history-*,.logstash_dead_letter,.ml*,grantofrepresentation_cases,caveat_cases,legacy_cases,standingsearch_cases,willlodgement_cases
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  ccd-logstash:
    image: hmctspublic.azurecr.io/ccd/logstash:probate-latest
    environment:
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx400m
      - XPACK_MONITORING_ENABLED=false
      - DB_URL=jdbc:postgresql://shared-database:5432/ccd_data?stringtype=unspecified&ssl=false
      - DB_USER=${DB_USERNAME}
      - DB_PWD=${DB_PASSWORD}
      - ES_DATA_NODES_URL=http://ccd-elasticsearch:9200
      - LOG_LEVEL=warn
    depends_on:
      - ccd-elasticsearch
      - shared-database

  dm-store:
    image: hmctspublic.azurecr.io/dm/store:latest
    environment:
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx256m
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://shared-database:5432/evidence
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - STORAGEACCOUNT_PRIMARY_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azure-storage-emulator-azurite:10000/devstoreaccount1
      - STORAGE_CONTAINER_DOCUMENT_CONTAINER_NAME=hmctstestcontainer
      - IDAM_S2S_BASE_URI=http://service-auth-provider-api:8080
      - ENABLE_TTL=false
      - ENABLE_METADATA_MIGRATION=false
    depends_on:
      - shared-database
      - service-auth-provider-api
      - make-container-call
    ports:
      - 5006:8080

  azure-storage-emulator-azurite:
    image: arafato/azurite
    ports:
      - 10000:10000
    environment:
      executable: "blob"
    volumes:
      - ccd-docker-azure-blob-data:/opt/azurite/folder

  make-container-call:
    image: byrnedo/alpine-curl
    command: --retry 10 --retry-connrefused -XPUT --verbose http://azure-storage-emulator-azurite:10000/devstoreaccount1/hmctstestcontainer?restype=container
    links:
      - azure-storage-emulator-azurite
    depends_on:
      - azure-storage-emulator-azurite

volumes:
  ccd-docker-azure-blob-data:
  esdata1:
    driver: local
