---
version: '3.5'

services:
  shared-database:
    image: postgres
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_MULTIPLE_DATABASES: ccd,ccd_user_profile,ccd_definition,ccd_data,ccd_definition_designer,div_scheduler
      DB_USERNAME:
      DB_PASSWORD:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5050:5432

  ccd-user-profile-api:
    image: "${CCD_USER_PROFILE_API_USE_LOCAL-hmctspublic.azurecr.io/}ccd/user-profile-api:${CCD_USER_PROFILE_API_TAG:-latest}"
    environment:
      JAVA_TOOL_OPTIONS: -Xms128m -Xmx400m
      USER_PROFILE_DB_HOST: shared-database
      USER_PROFILE_DB_PORT: 5432
      USER_PROFILE_DB_USERNAME: "${DB_USERNAME}"
      USER_PROFILE_DB_PASSWORD: "${DB_PASSWORD}"
      USER_PROFILE_DB_USE_SSL: "false"
      USER_PROFILE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_definition,ccd_admin
      IDAM_S2S_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - 4453:4453
    depends_on:
      - shared-database

  ccd-definition-store-api:
    image: "${CCD_DEFINITION_STORE_API_USE_LOCAL-hmctspublic.azurecr.io/}ccd/definition-store-api:${CCD_DEFINITION_STORE_API_TAG:-latest}"
    environment:
      JAVA_TOOL_OPTIONS: -Xms128m -Xmx400m
      DEFINITION_STORE_DB_HOST: shared-database
      DEFINITION_STORE_DB_PORT: 5432
      DEFINITION_STORE_DB_USERNAME: "${DB_USERNAME}"
      DEFINITION_STORE_DB_PASSWORD: "${DB_PASSWORD}"
      DEFINITION_STORE_DB_USE_SSL: "false"
      DEFINITION_STORE_IDAM_KEY:
      DEFINITION_STORE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_gw,ccd_admin,nfdiv_cms,nfdiv_cos
      USER_PROFILE_HOST: http://ccd-user-profile-api:4453
      IDAM_USER_URL: http://idam-api:5000
      IDAM_S2S_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
      REFORM_SERVICE_NAME: ccd-definition-store-api
      ELASTIC_SEARCH_ENABLED: "true"
      ELASTIC_SEARCH_HOST: "ccd-elasticsearch"
      ELASTIC_SEARCH_FAIL_ON_IMPORT: "true"
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - 4451:4451
    depends_on:
      - shared-database
      - ccd-user-profile-api

  ccd-data-store-api:
    image: "${CCD_DATA_STORE_API_USE_LOCAL-hmctspublic.azurecr.io/}ccd/data-store-api:${CCD_DATA_STORE_API_TAG:-latest}"
    environment:
      JAVA_TOOL_OPTIONS: -Xms128m -Xmx400m
      DATA_STORE_DB_HOST: shared-database
      DATA_STORE_DB_PORT: 5432
      DATA_STORE_DB_USERNAME: "${DB_USERNAME}"
      DATA_STORE_DB_PASSWORD: "${DB_PASSWORD}"
      DATA_STORE_DB_USE_SSL: "false"
      DATA_STORE_IDAM_KEY:
      DATA_STORE_S2S_AUTHORISED_SERVICES: ccd_gw,fpl_case_service,ccd_data,ccd_ps,nfdiv_cos,nfdiv_cms,payment-api,xui_webapp
      CCD_DM_DOMAIN: http://dm-store-aat.service.core-compute-aat.internal
      DEFINITION_STORE_HOST: http://ccd-definition-store-api:4451
      USER_PROFILE_HOST: http://ccd-user-profile-api:4453
      IDAM_USER_URL: http://idam-api:5000
      IDAM_S2S_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
      ELASTIC_SEARCH_ENABLED: "true"
      ELASTIC_SEARCH_HOSTS: ccd-elasticsearch:9200
      ELASTIC_SEARCH_DATA_NODES_HOSTS: "http://ccd-elasticsearch:9200"
      DATA_STORE_DEFAULT_LOG_LEVEL: INFO
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - 4452:4452
      - 5005:5005
    depends_on:
      - shared-database
      - ccd-user-profile-api
      - ccd-definition-store-api

  ccd-api-gateway:
    image: hmctspublic.azurecr.io/ccd/api-gateway-web:latest
    environment:
      IDAM_BASE_URL: http://idam-api:5000
      IDAM_USER_URL: http://idam-api:5000
      IDAM_S2S_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
      IDAM_SERVICE_KEY:
      IDAM_OAUTH2_LOGOUT_ENDPOINT: http://idam-api:5000/session/:token
      IDAM_OAUTH2_CLIENT_ID: ccd_gateway
      IDAM_OAUTH2_CLIENT_SECRET: "${CCD_OAUTH_SECRET}"
      IDAM_OAUTH2_TOKEN_ENDPOINT: http://idam-api:5000/oauth2/token
      PROXY_DOCUMENT_MANAGEMENT: http://dm-store-aat.service.core-compute-aat.internal
      ADDRESS_LOOKUP_TOKEN:
      PROXY_AGGREGATED: http://ccd-data-store-api:4452
      PROXY_DATA: http://ccd-data-store-api:4452
      PROXY_DEFINITION_IMPORT: http://ccd-definition-store-api:4451
      PROXY_DEFINITION_DATA: http://ccd-definition-store-api:4451/api/data
      PROXY_DEFINITION_DISPLAY: http://ccd-definition-store-api:4451/api/display
      PROXY_PAYMENTS: http://payment-api-aat.service.core-compute-aat.internal
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - 3453:3453
    depends_on:
      - ccd-user-profile-api
      - ccd-definition-store-api
      - ccd-data-store-api

  ccd-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    environment:
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx400m
      - ES_JAVA_OPTS= -Xms128m -Xmx400m
      - cluster.name=ccd-docker-es-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - action.auto_create_index=.security*,.watches,.triggered_watches,.watcher-history-*,.logstash_dead_letter,.ml*,grantofrepresentation_cases,caveat_cases,legacy_cases,standingsearch_cases,willlodgement_cases
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  ccd-logstash:
    image: hmctspublic.azurecr.io/ccd/logstash:ccd-divorce-logstash-latest
    environment:
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx400m
      - XPACK_MONITORING_ENABLED=false
      - DB_URL=jdbc:postgresql://shared-database:5432/ccd_data?stringtype=unspecified&ssl=false
      - DB_USER=${DB_USERNAME}
      - DB_PWD=${DB_PASSWORD}
      - ES_DATA_NODES_URL=http://ccd-elasticsearch:9200
      - LOG_LEVEL=warn
    depends_on:
      - ccd-elasticsearch
      - shared-database

  nfdiv-cos:
    build:
      context: ./nfdiv-case-orchestration-service/
    environment:
      UK_GOV_NOTIFY_API_KEY:
      IDAM_CITIZEN_USERNAME:
      IDAM_CITIZEN_PASSWORD:
      IDAM_CASEWORKER_USERNAME:
      IDAM_CASEWORKER_PASSWORD:
      IDAM_CLIENT_SECRET: "${OAUTH2_CLIENT_SECRET}"
      CASE_MAINTENANCE_SERVICE_API_BASEURL: http://nfdiv-cms:4010
      IDAM_API_URL: http://idam-api:5000
      IDAM_API_REDIRECT_URL: https://div-pfe-aat.service.core-compute-aat.internal/authenticated
      PAYMENT_API_BASEURL: http://payment-api-aat.service.core-compute-aat.internal
      PRD_API_BASEURL: http://rd-professional-api-aat.service.core-compute-aat.internal
      SEND_LETTER_SERIVCE_BASEURL: http://rpe-send-letter-service-aat.service.core-compute-aat.internal
      CASE_FORMATTER_SERVICE_API_BASEURL: http://div-cfs-aat.service.core-compute-aat.internal
      SERVICE_AUTH_PROVIDER_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
      DOCUMENT_GENERATOR_SERVICE_API_BASEURL: http://div-dgs-aat.service.core-compute-aat.internal
      FEES_AND_PAYMENTS_SERVICE_API_BASEURL: http://div-fps-aat.service.core-compute-aat.internal
      DOCUMENT_MANAGEMENT_STORE_URL: http://dm-store-aat.service.core-compute-aat.internal
      SERVICE_AUTH_SECRET: "${COS_SERVICE_KEY}"
      SCHEDULER_RE_CREATE: "true"
      FEATURE_DN_REFUSAL: "true"
      FEATURE_RESP_SOLICITOR_DETAILS: "true"
      DIV_SCHEDULER_DB_HOST: "shared-database"
      DIV_SCHEDULER_DB_PORT: "5432"
      DIV_SCHEDULER_DB_NAME: "div_scheduler"
      DIV_SCHEDULER_DB_USER_NAME: "${DB_USERNAME}"
      DIV_SCHEDULER_DB_PASSWORD: "${DB_PASSWORD}"
      FLYWAY_URL: "jdbc:postgresql://shared-database:5432/div_scheduler"
    ports:
      - 4012:4012
    depends_on:
      - shared-database

  nfdiv-cms:
    build:
      context: ./nfdiv-case-maintenance-service/
    environment:
      IDAM_API_BASEURL: http://idam-api:5000
      IDAM_API_REDIRECT_URL: https://div-pfe-aat.service.core-compute-aat.internal/authenticated
      IDAM_CASEWORKER_USERNAME:
      IDAM_CASEWORKER_PASSWORD:
      AUTH2_CLIENT_SECRET: "${OAUTH2_CLIENT_SECRET}"
      DRAFT_STORE_API_ENCRYPTION_KEY_VALUE: "${DRAFT_STORE_API_KEY}"
      AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
      DRAFT_STORE_API_BASEURL: http://draft-store-service-aat.service.core-compute-aat.internal
      CASE_FORMATTER_SERVICE_API_BASEURL: http://div-cfs-aat.service.core-compute-aat.internal
      CASE_DATA_STORE_BASEURL: http://ccd-data-store-api:4452
      AUTH_PROVIDER_SERVICE_CLIENT_KEY: "${CMS_SERVICE_KEY}"
      LOG_LEVEL: DEBUG
    ports:
      - 4010:4010
    depends_on:
      - ccd-data-store-api

  xui-manage-cases:
    image: "${XUI_MANAGE_CASES_USE_LOCAL-hmctspublic.azurecr.io/}xui/webapp:${XUI_MANAGE_CASES_TAG:-latest}"
    environment:
      FEATURE_APP_INSIGHTS_ENABLED: "true"
      FEATURE_SECURE_COOKIE_ENABLED: "false"
      FEATURE_REDIS_ENABLED: "false"
      JURISDICTIONS: AUTOTEST1,DIVORCE,PROBATE,BEFTA_JURISDICTION_3,BEFTA_JURISDICTION_2,BEFTA_JURISDICTION_1,IA,SSCS,BEFTA_MASTER
      MICROSERVICE: xui_webapp
      PROTOCOL: http
      XUI_ENV: local
      SERVICES_DOCUMENTS_API: http://dm-store-aat.service.core-compute-aat.internal
      SERVICES_PAYMENTS_URL: http://payment-api-aat.service.core-compute-aat.internal
      SERVICES_EM_ANNO_API: http://ccd-api-gateway:3453
      SERVICES_CCD_COMPONENT_API: http://ccd-api-gateway:3453
      SERVICES_CCD_DATA_STORE_API: http://ccd-data-store-api:4452
      SERVICES_IDAM_API_URL: http://idam-api:5000
      SERVICES_IDAM_CLIENT_ID: xuiwebapp
      SERVICES_IDAM_LOGIN_URL: http://idam-web-public:3501
      SERVICES_IDAM_INDEX_URL: /
      SERVICES_IDAM_OAUTH_CALLBACK_URL: /oauth2/callback
      SERVICES_S2S: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
      REDISCLOUD_URL: http://localhost:6780
      HEALTH_CCD_COMPONENT_API: http://ccd-api-gateway:3453/health
      HEALTH_CCD_DATA_API: http://ccd-data-store-api:4452/health
      APPINSIGHTS_INSTRUMENTATIONKEY: TESTVAR
      IDAM_SECRET: "${XUI_OAUTH_SECRET}"
      S2S_SECRET: "${XUI_SERVICE_KEY}"
      LAUNCH_DARKLY_CLIENT_ID: 1
    ports:
      - 3000:3000
    depends_on:
      - ccd-api-gateway
      - ccd-data-store-api

volumes:
  ccd-docker-azure-blob-data:
  esdata1:
    driver: local

networks:
  default:
      name: local-reform
